'''text = "Neo-Nazism consists of post-World War II militant social or political movements seeking to revive and implement the ideology of Nazism. Neo-Nazis seek to employ their ideology to promote hatred and attack minorities, or in some cases to create a fascist political state. It is a global phenomenon, with organized representation in many countries and international networks. It borrows elements from Nazi doctrine, including ultranationalism, racism, xenophobia, ableism, homophobia, anti-Romanyism, antisemitism, anti-communism and initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. In some European and Latin American countries, laws prohibit the expression of pro-Nazi, racist, anti-Semitic, or homophobic views. Many Nazi-related symbols are banned in European countries (especially Germany) in an effort to curtail neo-Nazism. The term neo-Nazism describes any post-World War II militant, social or political movements seeking to revive the ideology of Nazism in whole or in part. The term neo-Nazism can also refer to the ideology of these movements, which may borrow elements from Nazi doctrine, including ultranationalism, anti-communism, racism, ableism, xenophobia, homophobia, anti-Romanyism, antisemitism, up to initiating the Fourth Reich. Holocaust denial is a common feature, as is the incorporation of Nazi symbols and admiration of Adolf Hitler. Neo-Nazism is considered a particular form of far-right politics and right-wing extremism."

from summa.summarizer import summarize
# Define length of the summary as a proportion of the text
print(summarize(text, ratio=0.2))

summarize(text, words=50)

from summa import keywords
print("Keywords:\n",keywords.keywords(text))
# to print the top 3 keywords
print("Top 3 Keywords:\n",keywords.keywords(text,words=3))'''

#text = "The 1865 American Civil War marked a pivotal moment in the history of the United States. It was a protracted and devastating conflict that lasted from April 12, 1861, to April 9, 1865, resulting in significant political, social, and economic changes across the nation. The war had its roots in the long-standing disputes over issues like slavery, states' rights, and regional tensions between the North and the South. The Southern states, led by figures like Jefferson Davis, seceded from the Union and formed the Confederate States of America, underlining their commitment to preserving the institution of slavery. President Abraham Lincoln, a towering figure during this period, was determined to preserve the Union and end the conflict. His Emancipation Proclamation of 1863 declared that all slaves in Confederate-held territory were to be set free, fundamentally altering the war's purpose and widening the scope of the conflict. The war saw immense bloodshed, with countless battles fought, the most infamous being the Battle of Gettysburg. It involved the mobilization of armies on an unprecedented scale and left lasting scars on the land and its people. As the war progressed, the North's industrial might and resources began to take a toll on the Confederate forces. General Ulysses S. Grant's relentless campaigns, along with the naval blockade of Confederate ports, further weakened the South's ability to continue the struggle. Finally, on April 9, 1865, General Robert E. Lee surrendered to General Grant at Appomattox Court House, marking the end of the Civil War. The nation embarked on the path of reconstruction and reconciliation, aiming to heal the deep wounds inflicted during the conflict. The American Civil War left a profound impact on the country, resulting in the abolition of slavery, amendments to the Constitution, and a redefined sense of nationhood. It remains a subject of study and reflection, reminding us of the complex and often painful journey of a nation toward unity and equality."
#text = "Artificial Intelligence (AI) has emerged as a transformative force in the realm of healthcare, revolutionizing the way medical data is analyzed, diagnoses are made, and patient care is delivered. Through machine learning algorithms, AI has the capacity to process vast amounts of medical information, identifying patterns and making predictions at a speed and accuracy far beyond human capability. One of the most significant applications of AI in healthcare is in diagnostics. AI-powered systems can analyze medical images, such as X-rays, MRIs, and CT scans, with exceptional precision, aiding clinicians in the early detection and diagnosis of diseases. This not only expedites the diagnostic process but also potentially reduces human error, leading to more effective treatments. Moreover, AI is instrumental in personalized medicine, tailoring treatment plans to individual patients based on their unique genetic makeup and medical history. This targeted approach enhances efficacy while minimizing adverse effects. Beyond diagnostics and treatment, AI facilitates administrative tasks, streamlining processes such as scheduling, billing, and maintaining electronic health records. This efficiency allows healthcare professionals to focus more on patient care. While AI presents enormous opportunities, it also brings forth ethical considerations regarding data privacy, algorithm bias, and the potential replacement of certain human roles in healthcare. Striking a balance between technological advancement and human involvement remains a crucial aspect of its integration. In conclusion, the integration of AI in healthcare holds immense promise, enhancing diagnostic accuracy, treatment efficacy, and operational efficiency. As AI continues to evolve, its responsible and ethical application will be pivotal in shaping the future of healthcare."
text = "Renewable energy stands as a beacon of hope in the quest for sustainable and eco-friendly power sources. With the world’s increasing energy demands and the looming specter of climate change, the shift towards renewables has become not just a choice but a necessity. Solar power, a frontrunner in this arena, harnesses the sun’s inexhaustible energy, offering a clean and abundant source of electricity. Advancements in solar technology have made it more accessible and cost-effective, contributing significantly to reducing reliance on fossil fuels. Wind energy, another stalwart in the renewable energy landscape, utilizes the power of the wind to generate electricity. Wind farms, both onshore and offshore, have become emblematic of clean energy initiatives globally, providing a reliable source of power without the emissions associated with traditional energy sources. Hydropower, derived from the energy of flowing water, remains a stalwart in the renewable energy mix. It not only produces electricity but also aids in water management, irrigation, and flood control. However, its impact on local ecosystems and the need for large-scale infrastructure are subjects of ongoing debate and improvement. The beauty of these renewable sources lies in their ability to reduce carbon emissions, combat climate change, and offer long-term sustainability. Yet, challenges persist. Energy storage, grid integration, and intermittency issues are among the hurdles that necessitate continued innovation and investment. The future of energy is undeniably intertwined with the growth and evolution of renewable sources. As technology advances and policies evolve, the transition to a cleaner, more sustainable energy landscape becomes not just a possibility but an imperative for the well-being of our planet."

from summa.summarizer import summarize
# Define length of the summary as a proportion of the text
print(summarize(text, ratio=0.2))

summarize(text, words=50)

from summa import keywords
print("Keywords:\n",keywords.keywords(text))
# to print the top 3 keywords
print("Top 3 Keywords:\n",keywords.keywords(text,words=3))